language: java

jdk:
  - oraclejdk8

install:
  - mvn install -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test

notifications:
  email:
    on_success: never

sudo: required

services:
  - docker